[build-system]
requires = ["setuptools>=82.0.1", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyramid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cython>=3.2.5",
    "pygame>=2.6.1",
    "setuptools>=82.0.1",
    "pyramid",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
pyramid = {path=".", editable = true}
